# Generated by Django 3.2.13 on 2022-06-04 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории/товара')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('OFFER', 'Товар'), ('CATEGORY', 'Категория')], max_length=10, verbose_name='Тип')),
                ('price', models.BigIntegerField()),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='product_id_idx'),
        ),
    ]
