# Generated by Django 3.2.13 on 2022-06-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220604_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parents',
            new_name='parentId',
        ),
    ]
