# Generated by Django 3.2.13 on 2022-06-06 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_historicalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 12, 16, 30, 851565)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 6, 12, 16, 30, 851565)),
        ),
    ]
