# Generated by Django 3.2.13 on 2022-06-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220606_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField()),
                ('name', models.CharField(max_length=100, verbose_name='Название категории/товара')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('OFFER', 'Товар'), ('CATEGORY', 'Категория')], max_length=10, verbose_name='Тип')),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.producthistory')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.AddIndex(
            model_name='producthistory',
            index=models.Index(fields=['product_id'], name='product_history_product_id_idx'),
        ),
    ]
