# Generated by Django 3.2.13 on 2022-06-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220608_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'verbose_name': 'История изменений модели Product'},
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
