# Generated by Django 3.2.13 on 2022-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220611_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='price_changed',
            field=models.BooleanField(default=False),
        ),
    ]
