# Generated by Django 3.2.13 on 2022-06-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_producthistory_price_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
