# Generated by Django 3.2.13 on 2022-06-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220611_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='date_updated',
        ),
    ]
